### PR TITLE
86 create  event handler will sort list high to low

### LINKED ISSUE #86: Handle sorting food list by water usage low-to-high
We need to handle sorting the food list by water usage, low-to-high. This ticket will require the following:
- [ ] A sort function `sortLowHighWater` created in `/client/utils/sort.js`
- [ ] Update `mapStateToProps` in `FoodList.jsx` to handle `SORT_WATER_LOW` sortType (i.e. call your new function in `sort.js`

### PR DESCRIPTION
**Pull request by davidnicho**
Closes #86 
Create Water high low in utility folder.
Zero testing

### CODE REVIEW

**Review by jessica-morgan — DISMISSED** [review]
It seems you have written the action creator to sort by water usage rather than the event handler that will dispatch an action creator that will then tell the store to sort the list accordingly. 
For this ticket you will need to write the sort by water usage (high-low) _event handler_ which you can write in the utils folder and bring into `SortListDropdown` component, rather than writing the action itself. This event handler will dispatch the action creator `orderWaterLowHigh(selectedSortType)` when a sort type is selected from the drop down :)

**Comment by bryceknz** [comment]
Please see the updated ticket description #86 for a step-by-step 😊👍

**Comment by davidnicho** [comment]
Closes # 86
sort.js
Foodlist.jsx
testing sort.test

**Review by bryceknz — DISMISSED** [review]
Awesome work!

**Review by bryceknz — APPROVED** [review]

**Pull request merged**
