### PR TITLE
76 remove throwing of errors from client side code

### LINKED ISSUE #76: Remove throwing of Errors from client-side code
It looks like a few Errors are being thrown about on the client-side - not a good look for our customers! Let's fail a bit more gracefully... For now, we'd just like any errors that are caught to update the `error` property on the `info` part of the store.

You will need to:
- [ ] search for all instances of `throw` in the code. I count three at present, but there may be more!
- [ ] ensure that each component where an error is being thrown is connected to the redux store (we'll only need access to the dispatcher, not the client state)
- [ ] instead of throwing an error, let's dispatch the error message into... well, whichever is the relevant action! This part of the ticket is blocked by #98. I'm envisaging `AddFood` will dispatch the error message from the rejected promise straight into `addFoodError`, and `EditFood` will do the same, with specificity about which food failed on update.

### PR DESCRIPTION
**Pull request by CeliaAB**
Closes #76

### CODE REVIEW

**Review by bryceknz — CHANGES_REQUESTED** [review]
Lovely work! I've tested it and it all works fine 😊

There's just one thing... Since this PR was requested, someone's included `throw new Error` again in the client-side code! Please perform the same 'upgrade' as you have been doing already. The file in question is `/client/components/FoodDetails.jsx`.

**Comment by jennie-watson** [comment]
Change request done. Closes #76

**Review by bryceknz — APPROVED** [review]
Nice work!

**Comment by bryceknz** [comment]
@jennie-watson Don't forget to delete the branch!

**Pull request merged**
